"""Add status and due_at fields to tasks

Revision ID: 9f5878d9abef
Revises: ec4370fc48f5
Create Date: 2025-11-10 22:17:34.197629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5878d9abef'
down_revision: Union[str, Sequence[str], None] = 'ec4370fc48f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type if it doesn't exist
    bind = op.get_bind()
    task_status_enum = sa.Enum('BACKLOG', 'PLANNED', 'COMPLETED', 'REMOVED', name='task_status')
    task_status_enum.create(bind, checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', task_status_enum, server_default='BACKLOG', nullable=False))
    op.add_column('tasks', sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_column('tasks', 'due_at')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###

    # Drop the enum type created in upgrade (must run after dropping the column that uses it)
    bind = op.get_bind()
    task_status_enum = sa.Enum('BACKLOG', 'PLANNED', 'COMPLETED', 'REMOVED', name='task_status')
    task_status_enum.drop(bind, checkfirst=True)
