"""Add planned_start_at, planned_end_at, and planned_duration fields to Task

Revision ID: ae807134c28e
Revises: 9f5878d9abef
Create Date: 2025-11-10 23:05:10.572644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae807134c28e'
down_revision: Union[str, Sequence[str], None] = '9f5878d9abef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('planned_start_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('planned_end_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('planned_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'planned_duration')
    op.drop_column('tasks', 'planned_end_at')
    op.drop_column('tasks', 'planned_start_at')
    # ### end Alembic commands ###
