"""Test migration script

Revision ID: ec4370fc48f5
Revises: 1cf81a1539c0
Create Date: 2025-11-10 21:58:20.121519

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ec4370fc48f5"
down_revision: str | Sequence[str] | None = "1cf81a1539c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
