#!/usr/bin/env bash
set -euo pipefail

# -----------------------------
# Alembic migration helper
# -----------------------------
# Usage:
#   ./scripts/migrate.sh revision "Message"
#   ./scripts/migrate.sh upgrade
#   ./scripts/migrate.sh downgrade -1
#   ./scripts/migrate.sh stamp
# Run from repo root so docker compose finds docker-compose.yml.

COMMAND=${1:-}
MESSAGE=${2:-"autogenerated migration"}

# Determine if running inside Docker
if [ -f /.dockerenv ]; then
    # Inside container
    WORKDIR="/app"
    cd "$WORKDIR"

    case "$COMMAND" in
        revision)
            alembic revision --autogenerate -m "$MESSAGE"
            ;;
        upgrade)
            alembic upgrade head
            ;;
        downgrade)
            alembic downgrade "${3:--1}"
            ;;
        current)
            alembic current
            ;;
        history)
            alembic history
            ;;
        stamp)
            alembic stamp head
            ;;
        *)
            echo "Usage: $0 {revision|upgrade|downgrade|current|history|stamp} [message]"
            exit 1
            ;;
    esac
else
    # Outside container — use docker compose to run inside API container
    CONTAINER="api"
    DOCKER_CMD="docker compose exec $CONTAINER bash -lc"

    case "$COMMAND" in
        revision)
            $DOCKER_CMD "cd /app && alembic revision --autogenerate -m \"$MESSAGE\""
            ;;
        upgrade)
            $DOCKER_CMD "cd /app && alembic upgrade head"
            ;;
        downgrade)
            $DOCKER_CMD "cd /app && alembic downgrade ${3:--1}"
            ;;
        current)
            $DOCKER_CMD "cd /app && alembic current"
            ;;
        history)
            $DOCKER_CMD "cd /app && alembic history"
            ;;
        stamp)
            $DOCKER_CMD "cd /app && alembic stamp head"
            ;;
        *)
            echo "Usage: $0 {revision|upgrade|downgrade|current|history|stamp} [message]"
            exit 1
            ;;
    esac
fi
